version: "2"
services:
  mamute:
    image: jbasila/mamute:1.5.0
    environment:
      MYSQL_PASSWORD: mamute
      MAMUTE_PORT: 8080
    ports:
      - 8090:80
      - 8080:8080
    links:
      - mysql-mamute:mysql

  mysql-mamute:
    image: mysql:5.7.4
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: mamute
      MYSQL_USER: mamute
      MYSQL_PASSWORD: mamute
    expose:
      - 3306
volumes:
  mysql-data:
