version: "2"
services:
  mamute:
    image: jbasila/mamute:1.5.0
    environment:
      MYSQL_PASSWORD: mamute
      MAMUTE_PORT: 8085
      MAMUTE_HOST: 52.172.6.58
      MAMUTE_ATTACHMENTS_PATH: /tmp 
    ports:
      - 8095:80
      - 8085:8085
    links:
      - mysql-mamute:mysql

  mysql-mamute:
    image: mysql:5.7.4
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: mamute
      MYSQL_USER: mamute
      MYSQL_PASSWORD: mamute
    expose:
      - 3306