apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mamute
  name: mamute
spec:
  ports:
  - name: "8095"
    port: 8095
    targetPort: 80
  - name: "8085"
    port: 8085
    targetPort: 8085
  selector:
    io.kompose.service: mamute
status:
  loadBalancer: {}
