apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mamute
  name: mamute
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mamute
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mamute
    spec:
      containers:
      - env:
        - name: MAMUTE_PORT
          value: "8080"
        - name: MYSQL_PASSWORD
          value: mamute
        image: jbasila/mamute:1.5.0
        imagePullPolicy: ""
        name: mamute
        ports:
        - containerPort: 80
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
