apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert -f E:\repos\Github\mamute\docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-mamute
  name: mysql-mamute
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert -f E:\repos\Github\mamute\docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-mamute
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: mamute
        - name: MYSQL_PASSWORD
          value: mamute
        - name: MYSQL_ROOT_PASSWORD
          value: secretpassword
        - name: MYSQL_USER
          value: mamute
        image: mysql:5.7.4
        name: mysql-mamute
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      restartPolicy: Always
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
status: {}
